WIP: IDM docs
ubccr/ccrdocs pull request #10
Opened 2022-11-11 21:35 UTC by dsajdak

documentation for IDM portal, creating accounts, 2FA management, getting started page, new index page

2022-11-22 18:45 UTC, dsajdak commented on pages/2fa.md
> +[See these instructions for logging into CCR's portals with 2FA enabled](portals/idm/#logging-in-with-two-factor-authentication)
this link doesn't work.  I'm fixing it in another PR

2022-11-23 02:23 UTC, aebruno requested changes
Content looks great! Found a bunch of invalid links however. When linking to a page you should link to the markdown file. [See here](https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages) for more info on page linking in mkdocs. 

Looks like anywhere you link to a page you need to fix. Added a few comments on how to fix but will need to update all page links. For example:

This:
 ` [See here](getting-access/#requesting-an-allocation-in-coldfront)`

Should be:

`[See here](getting-access.md#requesting-an-allocation-in-coldfront)`

2022-11-23 02:23 UTC, aebruno commented on pages/2fa.md
> +    Changing phones? If you won't have access to both devices, disable 2FA on your CCR account prior to swapping phones. When you get your new phone [follow these instructions](portals/idm/#managing-
Fix page link, should be: `[See these instructions for logging into CCR's portals with 2FA enabled](portals/idm.md#logging-in-with-two-factor-authentication)`

2022-11-23 02:23 UTC, aebruno commented on pages/getting-access.md
> +Users with UB or Roswell Park email addresses can create themselves a CCR user account following [these directions](../portals/idm/#create-a-ccr-system-account).  Once your account is created, make s
Fix page link, should be: `[these directions](portals/idm.md#create-a-ccr-system-account)` and `[follow the instructions for enabling two factor authentication](portals/idm.md#managing-two-factor-authentication)`

2022-11-23 02:23 UTC, aebruno commented on pages/getting-access.md
> +ColdFront is CCR's resource and allocation management system.  ColdFront manages all of CCR's resources and the access all users have to those resources.  Faculty members (Principal investigators) mu
Fix page link, should be: `[More details about ColdFront can be found here](portals/coldfront.md)`

2022-11-23 02:23 UTC, aebruno commented on pages/getting-started.md
> +     - Get instructions for how to [connect to our HPC systems with SSH](../hpc/login)
Fix page links.. need to link to md file, for example: `hpc/storage.md`

2022-11-23 02:23 UTC, aebruno commented on pages/getting-started.md
> +    You must be on an active allocation for the resource(s) you want to use.  [More info here](../getting_access)
This link is not correct. Should link to md file

2022-11-23 02:23 UTC, aebruno commented on pages/hpc/login.md
> +- An active allocation for the resource in ColdFront - No allocation?  [See here](getting-access/#requesting-an-allocation-in-coldfront)
Fix link

2022-11-23 02:23 UTC, aebruno commented on pages/hpc/login.md
> +management portal, [following these instructions](portals/idm/#create-a-ccr-system-account).  Once an account is created, users must be added to an active allocation for one of the CCR clusters in or
Fix link

2022-11-23 19:15 UTC, aebruno requested changes
Find a few minor tweaks

2022-11-23 19:15 UTC, aebruno commented on pages/index.md
> +    - [LakeEffect Cloud Quick Start](cloud/lake-effect)
These links need fixing.. missing *.md  should be `cloud/lake-effect.md` .. etc.

2022-11-23 19:15 UTC, aebruno commented on mkdocs.yml
>      - Logging In: hpc/login.md
Let's add `hpc/viz.md` to the nav

2022-11-23 21:41 UTC, aebruno approved these changes

2022-11-23 21:41 UTC, merged