R Perl personal package installs
ubccr/ccrdocs pull request #22
Opened 2023-01-19 19:29 UTC by dsajdak

This documents how users can install their own R libraries and Perl modules

2023-01-20 20:55 UTC, jbednasz approved these changes

2023-01-24 15:40 UTC, aebruno approved these changes

2023-01-24 15:41 UTC, aebruno requested changes
Please fix conflicts

2023-01-24 16:01 UTC, dsajdak commented
@aebruno I think the conflicts are all resolved now

2023-01-24 16:01 UTC, aebruno approved these changes

2023-01-24 16:02 UTC, merged