Python docs
ubccr/ccrdocs pull request #80
Opened 2024-05-01 19:46 UTC by ANekhai

My draft of documentation for using Python on the HPC. The bulk of the changes live on their own page. I've updated the onDemand docs to include using VSCode and Python and fixed a link in the available software page to point to venv documentation.

Any suggestions for changes and modifications are welcome! I've included sections for FAQs and AI/ML stuff on the python page. I'm happy to expand on these if necessary, or to merge them into other sections if things are too busy!

2024-05-03 12:35 UTC, aebruno approved these changes

2024-05-07 16:04 UTC, dsajdak requested changes
@ANekhai as we discussed here's my full review.  Please verify that the links I added actually work.  :)  I tend to get the formatting wrong at least once!

2024-05-15 13:52 UTC, dsajdak requested changes
@ANekhai this looks fantastic!  There's just one small issue remaining before we publish.

2024-05-15 13:52 UTC, dsajdak commented on pages/portals/ood.md
> +There are a few oddities to note about how VSCode functions at CCR:
This section is still not showing up as a list - they're all in a single paragraph

2024-05-15 14:49 UTC, dsajdak approved these changes
LGTM!

2024-05-15 14:49 UTC, merged